app/blog/urls.py
from django.urls import path
from .views import Index, PostDetail, YandexTurbo, ParceObjects
from .custom_sitemap import custom_sitemap

app_name = 'blog'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('post/<slug:slug>', PostDetail.as_view(), name='detail'),
    path('urls', custom_sitemap, name='url'),
    path('yandex/turbo', YandexTurbo.as_view(), name='turbo'),
    path('create', ParceObjects.as_view(), name='create')
]

app/wpreboot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blog/models.py
from django.db import models
from pytils.translit import slugify

from ckeditor_uploader.fields import RichTextUploadingField


class Post(models.Model):
    id = models.BigAutoField(primary_key=True)
    image = models.ImageField(upload_to='media/', verbose_name='Изображение', )
    title = models.CharField(max_length=500, verbose_name='Заголовок поста', )
    content = RichTextUploadingField(verbose_name='Содержимое поста', )
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    slug = models.SlugField(max_length=200, unique=True, null=False, blank=False, default=slugify(title), verbose_name='Ссылка')

    class Meta:
        verbose_name = 'Пост на сайте'
        verbose_name_plural = 'Посты на сайте'
        ordering = ['-id']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self, **kwargs):
        return f'/post/{self.slug}'


class Galery(models.Model):
    image = models.ImageField(upload_to='galery', verbose_name='Изображение', )
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images', default=None)

app/blog/views.py
from urllib3.exceptions import InsecureRequestWarning
from urllib3 import disable_warnings
from django.core.files.base import File
from django.core.files.temp import NamedTemporaryFile
from django.views.generic import ListView, TemplateView
from pytils.translit import slugify
from randomfilestorage.storage import RandomFileSystemStorage
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from blog.models import Post, Galery

import requests
import re


class Index(TemplateView):
    """
    Класс отображения главной страницы
    использует методы контекстной обработки модели
    """
    template_name = 'theme/page/index.html'

    def get_context_data(self, **kwargs):
        slider = Post.objects.order_by('-date').order_by("?")[0:4]
        post = Post.objects.order_by('-date')[0:6]

        context = {
            'slider': slider,
            'post': post
        }
        return context


class PostDetail(TemplateView):
    """
    Класс отображения страницы детального просмотра поста
    использует методы контекстной обработки модели
    """
    template_name = 'theme/page/detail.html'

    def get_context_data(self, **kwargs):
        post = Post.objects.get(slug=kwargs['slug'])
        share = Post.objects.order_by('-date').order_by("?")[0:8]
        share_left = Post.objects.order_by('-date').order_by("?")[0:5]
        context = {
            'post': post,
            'share': share,
            'share_left': share_left,
        }
        return context


class YandexTurbo(ListView):
    """
    Класс отображения страницы плагина yandex_turbo
    использует методы стандартный метод обработки модели
    и пагинацию на условии: 1000 постов на 1 странице
    """
    template_name = 'theme/addon/yandex_turbo/turbo.xml'
    model = Post
    context_object_name = 'turbo'
    paginate_by = 1000


# Объявление переменной для библиотеки django-random-filestorage
random_storage = RandomFileSystemStorage(location='/media/')


class ParceObjects(APIView):
    """
    Класс DRF создания поста в блог используя API
    """
    post_content = ""
    post_image_list = ""

    def change_content(self, galery: list, post):
        content = self.post_content
        for tag in range(0, len(content)):
            if 'img' in content[tag]:
                matches = len(re.findall(r'\ssrc="([^"]+)"', content[tag]))
                mapping = dict(zip(self.post_image_list[:matches], galery[:matches]))

                del self.post_image_list[:matches]
                del galery[:matches]

                for image_src, image_dst in mapping.items():
                    content[tag] = content[tag].replace(image_src, image_dst)

        content = "".join(content)

        Post.objects.filter(id=post.id).update(content=content)

    def save_images_to_galery(self, title, images: list, post):
        count = 0
        galery = []
        disable_warnings(InsecureRequestWarning)
        for image in images:  # получаю список с ссылками на фото
            count += 1
            img_temp = NamedTemporaryFile()
            req = requests.get(image, verify=False).content
            img_temp.write(req)
            img_temp.flush()
            photo = Galery.objects.create(image=File(img_temp, name=f'{title}-{count}.jpg'), post=post)
            galery.append(photo.image.url)

        self.change_content(galery, post)

    def post(self, request):
        try:
            form = request.data
            title = form['title']
            self.post_content = form['content']
            self.post_image_list = form['img_list']
            slug = slugify(title)
            amount_of_posts = Post.objects.all().count()
            slug = f'{slug}-{int(amount_of_posts) + 1}'
            img_temp = NamedTemporaryFile()
            req = requests.get(form['image'], verify=False).content
            img_temp.write(req)
            img_temp.flush()
            post = Post.objects.create(title=form['title'], content="".join(form['content']),
                                       image=File(img_temp, name=f'{title}.jpg'),
                                       slug=slug)

            self.save_images_to_galery(title, self.post_image_list, post)

            return Response('Post Created', status=status.HTTP_201_CREATED)
        except Exception as e:
            return Response(e, status=status.HTTP_400_BAD_REQUEST)

app/templates/theme/addon/custom_sitemap/sitemap.html
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:html="http://www.w3.org/TR/REC-html40" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<head>
    <title>XML Sitemap</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="/static/css/sitemap.css">
</head>
<body>
<div id="content">
    <h1>XML Sitemap</h1>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a type="button" class="btn btn-primary" href="?page=1">&laquo; first</a>
            <a type="button" class="btn btn-primary" href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
            <a type="button" class="btn btn-primary" href="?page={{ page_obj.next_page_number }}">next</a>
            <a type="button" class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        <span class="expl">
            <a style="color: black">Pages:</a>
            {% for p in page_obj.paginator.page_range %}
                {% if page_obj.number == p %}
                    <a href="?page={{ p }}" style="color: #00d084">{{ p }}</a>
                {% else %}
                    <a href="?page={{ p }}">{{ p }}</a>
                {% endif %}
            {% endfor %}
        </span>
    </div>

    <table id="sitemap" cellpadding="3">
        <thead>
        <tr>
            <th width="80%">
                URL
            </th>
            <th title="Last Modification Time" width="15%">
                Last Mod.
            </th>
        </tr>
        </thead>
        <tbody>
        {% for serv in page_obj  %}
            <tr>
                <td>
                    <a href="{% url 'blog:detail' serv.slug %}">{{request.get_host}}{% url 'blog:detail' serv.slug %}</a>
                </td>
                <td>{{ serv.date.ctime }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</body>
</html>

app/templates/theme/block/footer.html
<div id="clearfy-cookie" class="clearfy-cookie clearfy-cookie-hide clearfy-cookie--bottom">
    <div class="clearfy-cookie-container">
        Этот сайт использует cookie для хранения данных. Продолжая использовать сайт, Вы даете свое согласие на работу с этими файлами. <button id="clearfy-cookie-accept" class="clearfy-cookie-accept">OK</button>
    </div>
</div>

app/templates/theme/block/head.html
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1" />
<meta name="description" content="Советы и идеи" />
<link rel="canonical" href="https://my-tips.ru/" />
<meta property="og:locale" content="ru_RU" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Копилка советов" />
<meta property="og:description" content="Советы и идеи" />
<meta property="og:url" content="https://my-tips.ru/" />
<meta property="og:site_name" content="Копилка советов" />
<meta name="twitter:card" content="summary_large_image" />
<link rel="stylesheet" id="google-fonts-css" href="https://fonts.googleapis.com/css?family=Montserrat%3A400%2C400i%2C700&#038;subset=cyrillic&#038;display=swap" media="all" />
<link rel="stylesheet" id="reboot-style-css" href="/static/css/style.min.css" media="all" />
<link rel="stylesheet"  href="/static/css/addon.css" media="all" />
<script src="/static/js/jquery.min.js" id="jquery-core-js"></script>
<link rel="preload" href="/static/fonts/wpshop-core.ttf" as="font" crossorigin />
<link rel="icon" href="/static/img/cropped-ets_logo-32x32.png" sizes="32x32" />
<link rel="icon" href="/static/img/cropped-ets_logo-192x192.png" sizes="192x192" />
<link rel="apple-touch-icon" href="/static/img/cropped-ets_logo-180x180.png" />
<meta name="msapplication-TileImage" content="/static/img/cropped-ets_logo-270x270.png" />

app/templates/theme/block/script.html
<script>
    var pseudo_links = document.querySelectorAll(".pseudo-clearfy-link");
    for (var i = 0; i < pseudo_links.length; i++) {
        pseudo_links[i].addEventListener("click", function (e) {
            window.open(e.target.getAttribute("data-uri"));
        });
    }
</script>
<script>
    function disable_keystrokes(e) {
        if (e.ctrlKey || e.metaKey) {
            var key;
            if (window.event) key = window.event.keyCode;
            else key = e.which;
            if (key == 67 || key == 88 || key == 65 || key == 85 || key == 83) return false;
            else return true;
        }
    }
    document.onkeydown = disable_keystrokes;
</script>
<script>
    function disableSelection(target) {
        if (typeof target.onselectstart != "undefined")
            target.onselectstart = function () {
                return false;
            };
        else if (typeof target.style.MozUserSelect != "undefined") target.style.MozUserSelect = "none";
        else
            target.onmousedown = function () {
                return false;
            };
        target.style.cursor = "default";
    }
    disableSelection(document.body);
</script>
<script>
    document.oncontextmenu = function () {
        return false;
    };
</script>
<script>
    document.addEventListener("copy", (event) => {
        var pagelink = "\nИсточник: https://everytips.ru";
        event.clipboardData.setData("text", document.getSelection() + pagelink);
        event.preventDefault();
    });
</script>
<script type="text/javascript" id="reboot-scripts-js-extra">
    /* <![CDATA[ */
    var settings_array = { rating_text_average: "\u0441\u0440\u0435\u0434\u043d\u0435\u0435", rating_text_from: "\u0438\u0437", lightbox_display: "1", sidebar_fixed: "" };
    var wps_ajax = { url: "https:\/\/everytips.ru\/wp-admin\/admin-ajax.php", nonce: "194aa57be4" };
    /* ]]> */
</script>
<script src="/static/js/scripts.min.js" id="reboot-scripts-js"></script>
<script src="/static/js/swiper.min.js" id="reboot-swiper-js"></script>
<script>
    var cookie_clearfy_hide = document.cookie.replace(/(?:(?:^|.*;\s*)clearfy_cookie_hide\s*\=\s*([^;]*).*$)|^.*$/, "$1");
    if (!cookie_clearfy_hide.length) {
        document.getElementById("clearfy-cookie").classList.remove("clearfy-cookie-hide");
    }
    document.getElementById("clearfy-cookie-accept").onclick = function () {
        document.getElementById("clearfy-cookie").className += " clearfy-cookie-hide";
        var clearfy_cookie_date = new Date(new Date().getTime() + 31536000 * 1000);
        document.cookie = "clearfy_cookie_hide=yes; path=/; expires=" + clearfy_cookie_date.toUTCString();
        setTimeout(function () {
            document.getElementById("clearfy-cookie").parentNode.removeChild(document.getElementById("clearfy-cookie"));
        }, 300);
    };
</script>
<!-- Initialize Swiper -->
<script>
    var wpshopSwiperThumbs = new Swiper(".js-swiper-home-thumbnails", {
        spaceBetween: 10,
        slidesPerView: 4,
        freeMode: true,
        loopedSlides: 5, //looped slides should be the same
        watchSlidesVisibility: true,
        watchSlidesProgress: true,
        breakpoints: {
            1024: {
                slidesPerView: 4,
            },
            900: {
                slidesPerView: 3,
            },
            760: {
                slidesPerView: 2,
            },
            600: {
                slidesPerView: 1,
            },
        },
    });

    var wpshopSwiper = new Swiper(".js-swiper-home", {
        spaceBetween: 30,
        loop: true,
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
        },
        autoplay: {
            delay: 3500,
            disableOnInteraction: true,
        },
        thumbs: {
            swiper: wpshopSwiperThumbs,
        },
        loopedSlides: 5, //looped slides should be the same
    });
</script>
<script>
    var pseudo_links = document.querySelectorAll(".pseudo-clearfy-link");
    for (var i = 0; i < pseudo_links.length; i++) {
        pseudo_links[i].addEventListener("click", function (e) {
            window.open(e.target.getAttribute("data-uri"));
        });
    }
</script>
<script>
    function disable_keystrokes(e) {
        if (e.ctrlKey || e.metaKey) {
            var key;
            if (window.event) key = window.event.keyCode;
            else key = e.which;
            if (key == 67 || key == 88 || key == 65 || key == 85 || key == 83)
                return false;
            else return true;
        }
    }
    document.onkeydown = disable_keystrokes;
</script>
<script>
    function disableSelection(target) {
        if (typeof target.onselectstart != "undefined")
            target.onselectstart = function () {
                return false;
            };
        else if (typeof target.style.MozUserSelect != "undefined")
            target.style.MozUserSelect = "none";
        else
            target.onmousedown = function () {
                return false;
            };
        target.style.cursor = "default";
    }
    disableSelection(document.body);
</script>
<script>
    document.oncontextmenu = function () {
        return false;
    };
</script>
<script>
    document.addEventListener("copy", (event) => {
        var pagelink =
            "\nИсточник: https://everytips.ru/5-zakonov-karmy-kotorye-podskazhut-chto-vy-delaete-ne-tak";
        event.clipboardData.setData("text", document.getSelection() + pagelink);
        event.preventDefault();
    });
</script>
<script type="text/javascript" id="wp-postviews-cache-js-extra">
    /* <![CDATA[ */
    var viewsCacheL10n = {
        admin_ajax_url: "https:\/\/everytips.ru\/wp-admin\/admin-ajax.php",
        post_id: "87742",
    };
    /* ]]> */
</script>
<script
        src="https://everytips.ru/wp-content/plugins/wp-postviews/postviews-cache.js"
        id="wp-postviews-cache-js"
></script>
<script type="text/javascript" id="reboot-scripts-js-extra">
    /* <![CDATA[ */
    var settings_array = {
        rating_text_average: "\u0441\u0440\u0435\u0434\u043d\u0435\u0435",
        rating_text_from: "\u0438\u0437",
        lightbox_display: "1",
        sidebar_fixed: "",
    };
    var wps_ajax = {
        url: "https:\/\/everytips.ru\/wp-admin\/admin-ajax.php",
        nonce: "194aa57be4",
    };
    /* ]]> */
</script>
<script
        src="https://everytips.ru/wp-content/themes/reboot/assets/js/scripts.min.js"
        id="reboot-scripts-js"
></script>
<script
        src="https://everytips.ru/wp-includes/js/comment-reply.min.js"
        id="comment-reply-js"
></script>

app/templates/theme/layout/main.html
<!DOCTYPE html>
<html lang="ru-RU">
<head>
    {% include 'theme/block/head.html' %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body data-rsssl="1" class="{% block body %}{% endblock %}">
<div id="page" class="site">
    {% block content %}
    {% endblock %}
</div>
<!-- #page -->
{% include 'theme/block/footer.html' %}
{% include 'theme/block/script.html' %}
</body>
</html>

app/templates/theme/page/detail.html
{% extends 'theme/layout/main.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block body %}post-template-default single single-post postid-87742 single-format-standard wp-embed-responsive sidebar-right{% endblock %}

{% block content %}
    <a class="skip-link screen-reader-text" href="#content">
        Перейти к содержанию
    </a>
    <header id="masthead" class="site-header full">
        <div class="site-header-inner fixed"></div>
    </header>
    <!-- #masthead -->
    <nav id="site-navigation" class="main-navigation full" style="display: none">
        <div class="main-navigation-inner fixed">
            <ul id="header_menu"></ul>
        </div>
    </nav>
    <div class="container header-separator"></div>
    <div class="mobile-menu-placeholder js-mobile-menu-placeholder"></div>
    <div id="content" class="site-content fixed">
        <div class="site-content-inner">
            <div id="primary" class="content-area" itemscope itemtype="http://schema.org/Article">
                <main id="main" class="site-main article-card">
                    <article id="post-87742" class="article-post post-87742 post type-post status-publish format-standard has-post-thumbnail">
                        <h1 class="entry-title" itemprop="headline">
                            {{ post.title }}
                        </h1>
                        <div class="entry-content" itemprop="articleBody">
                  <span itemprop="image" itemscope="" itemtype="https://schema.org/ImageObject">
                    <span itemprop="image" itemscope="" itemtype="https://schema.org/ImageObject">
                      <span itemprop="image" itemscope="" itemtype="https://schema.org/ImageObject">
                        <meta itemprop="width" content="750" />
                        <meta itemprop="height" content="440" />
                      </span>
                      <meta itemprop="width" content="750" />
                      <meta itemprop="height" content="440" /> </span>
                      <meta itemprop="width" content="750" />
                    <meta itemprop="height" content="440" />
                  </span>
                            <div class="container" style="margin-top: 20px;">
                                {{ post.content|safe }}
                            </div>
                        </div>
                        <!-- .entry-content -->
                    </article>
                    <div
                            itemprop="publisher"
                            itemscope
                            itemtype="https://schema.org/Organization"
                            style="display: none"
                    >
                        <div
                                itemprop="logo"
                                itemscope
                                itemtype="https://schema.org/ImageObject"
                        >
                            <img
                                    itemprop="url image"
                                    src="https://1beauty-life.ru/wp-content/uploads/2020/04/vserg5ew.png"
                                    alt="Копилка советов"
                            />
                        </div>
                        <meta itemprop="name" content="Копилка советов" />
                        <meta itemprop="telephone" content="Копилка советов" />
                        <meta itemprop="address" content="https://everytips.ru" />
                    </div>
                </main>
                <!-- #main -->
            </div>
            <!-- #primary -->
            <aside
                    id="secondary"
                    class="widget-area"
                    itemscope
                    itemtype="http://schema.org/WPSideBar"
            >
                <div class="sticky-sidebar js-sticky-sidebar">
                    <div id="search-2" class="widget widget_search">
                        <div class="post-cards post-cards--vertical">
                            <h3>Интересные статьи</h3>
                            {% for serv in share_left %}
                                <div class="post-card post-card--related">
                                    <div class="post-card__thumbnail">
                                        <a href="{% url 'blog:detail' serv.slug %}">
                                            <img
                                                    class="image_post"
                                                    width="335"
                                                    height="220"
                                                    src="{{ serv.image.url }}"
                                                    class="attachment-reboot_small size-reboot_small wp-post-image"
                                                    alt="Черновик"
                                                    loading="lazy"
                                            />
                                        </a>
                                    </div>
                                    <div class="post-card__title">
                                        <a href="{% url 'blog:detail' serv.slug %}">
                                            {{ serv.title }}
                                        </a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div
                            id="custom_html-2"
                            class="widget_text widget widget_custom_html"
                    >
                        <div class="textwidget custom-html-widget">
                            <div
                                    id="cnt_rb_243495"
                                    class="cnt32_rl_bg_str"
                                    data-id="243495"
                            ></div>
                        </div>
                    </div>
                </div>
            </aside>
            <!-- #secondary -->
            <div id="related-posts" class="related-posts fixed">
                <div class="related-posts__header">Вам также может понравиться</div>
                <div class="post-cards post-cards--vertical">
                    {% for serv in share %}
                        <div class="post-card post-card--related">
                            <div class="post-card__thumbnail">
                                <a href="{% url 'blog:detail' serv.slug %}">
                                    <img
                                            class="image_post"
                                            width="335"
                                            height="220"
                                            src="{{ serv.image.url }}"
                                            class="attachment-reboot_small size-reboot_small wp-post-image"
                                            alt="Черновик"
                                            loading="lazy"
                                    />
                                </a>
                            </div>
                            <div class="post-card__title">
                                <a href="{% url 'blog:detail' serv.slug %}">
                                    {{ serv.title }}
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!--.site-content-inner-->
    </div>
    <!--.site-content-->
    <div class="site-footer-container">
        <footer id="colophon" class="site-footer site-footer--style-gray full">
            <div class="site-footer-inner fixed">
                <div class="footer-bottom">
                    <div class="footer-info">
                        © 2022 Копирование материалов разрешено только с указанием
                        активной ссылки на первоисточник.
                    </div>
                </div>
            </div>
        </footer>
        <!--.site-footer-->
    </div>
    <button
            type="button"
            class="scrolltop js-scrolltop"
            data-mob="on"
    ></button>
{% endblock %}

app/templates/theme/page/index.html
{% extends 'theme/layout/main.html' %}

{% block title %}Копилка советов - Советы и идеи{% endblock %}
{% block body %}home blog wp-embed-responsive sidebar-none{% endblock %}
{% block content %}
    <!-- #header -->
    <header id="masthead" class="site-header full">
        <div class="site-header-inner fixed">
        </div>
    </header>
    <!-- #main-header-padding -->
    <nav id="site-navigation" class="main-navigation full" style="display: none;">
        <div class="main-navigation-inner fixed">
            <ul id="header_menu">
            </ul>
        </div>
    </nav>
    <!-- #Container | NotWork -->
    <div class="container header-separator"></div>
    <!-- # Mobil menu | NotWork -->
    <div class="mobile-menu-placeholder js-mobile-menu-placeholder"></div>
    <div class="container">
        <div class="card-slider-container swiper-container js-swiper-home">
            <div class="swiper-wrapper">
                {% for serv in slider %}
                    <div class="swiper-slide">
                        <a href="{% url 'blog:detail'  serv.slug %}">
                            <div class="card-slider__image" style="background-image: url({{ serv.image.url }});"></div>
                            <div class="card-slider__body">
                                <div class="card-slider__body-inner">
                                    <span class="card-slider__category"></span>
                                    <div class="card-slider__title">{{ serv.title }}</div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div class="swiper-pagination"></div>
            <div class="swiper-button-next swiper-button-white"></div>
            <div class="swiper-button-prev swiper-button-white"></div>
        </div>

        <div class="slider-thumbnails swiper-container js-swiper-home-thumbnails">
            <div class="swiper-wrapper">
                {% for serv in slider %}
                    <div class="swiper-slide">
                        <div class="slider-thumbnails__slide" style="background-image: url({{ serv.image.url }});">
                            <span class="slider-thumbnails__title">{{ serv.title }}</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div id="content" class="site-content fixed">
        <div class="site-content-inner">
            <div id="primary" class="content-area">
                <main id="main" class="site-main">
                    <div class="section-block section-posts section-preset--bgi-2 is-show-thumbnails-true">
                        <div class="post-cards post-cards--grid">
                            {% for serv in post %}
                                <div class="post-card post-card--grid w-animate" data-animate-style="fadeinup">
                                    <a href="{% url 'blog:detail' serv.slug %}">
                                        <div class="post-card__thumbnail">
                                            <img
                                                    class="image-main"
                                                    width="335"
                                                    height="220"
                                                    src="{{ serv.image.url }}"
                                                    class="attachment-reboot_small size-reboot_small wp-post-image"
                                                    alt="{% url 'blog:detail' serv.slug %}"
                                                    loading="lazy"
                                                    itemprop="image"
                                                    href="{% url 'blog:detail' serv.slug %}"
                                            />
                                            <span itemprop="articleSection" class="post-card__category"></span>
                                        </div>
                                    </a>
                                    <div class="post-card__body">
                                        <div class="post-card__title" itemprop="name">
                    <span itemprop="headline">
                        <a href="{% url 'blog:detail' serv.slug %}">{{ serv.title }}</a>
                    </span>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <!--.post-cards-->
                    </div>
                    <!--.section-posts-->
                </main>
                <!-- #main -->
            </div>
            <!-- #primary -->
        </div>
        <!--.site-content-inner-->
    </div>
    <!--.site-content-->
    <div class="site-footer-container">
        <footer id="colophon" class="site-footer site-footer--style-gray full">
            <div class="site-footer-inner fixed">
                <div class="footer-bottom"><div class="footer-info">
                    © 2022 Копирование материалов разрешено только с указанием активной ссылки на первоисточник.
                </div>
                </div>
            </div>
        </footer>
        <!--.site-footer-->
    </div>
{% endblock %}